[package]
name = "audiowarden"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
env_logger = "0.10.0"
log = "0.4.20"
url = "2.4.1"
