name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus at-spi2-core
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all --check
      # For now, we treat all warnings as errors: Maybe this is a bit too strict, will see how it turns out.
      - name: Run clippy
        run: cargo clippy -- -D warnings
